'use client';
import { FormEvent, useEffect, useState } from 'react';

type Onboarding = { consent: { required: boolean; policy_version: string }; uploads: { enabled: boolean }; identity_verification: { enabled: boolean }; settlement: { enabled: boolean } };
type Overview = { contributions: { id: string; type: string; status: string; reward: string }[]; reward_policy: string; settlement: { enabled: boolean; network: string | null } };
type Task = { id: string; title: string; instructions: string; kind: string; reward_work: number; client_name: string };

async function json<T>(url: string, init?: RequestInit): Promise<T> { const response = await fetch(url, init); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? 'Request failed'); return body; }
export function Portal() {
  const [onboarding, setOnboarding] = useState<Onboarding>(); const [overview, setOverview] = useState<Overview>(); const [tasks, setTasks] = useState<Task[]>([]);
  const [reply, setReply] = useState('I can help you get started.'); const [question, setQuestion] = useState(''); const [wallet, setWallet] = useState('Connect wallet'); const [taskStatus, setTaskStatus] = useState('Select a task to view its preview state.'); const [selectedTask, setSelectedTask] = useState<Task>(); const [workerName, setWorkerName] = useState(''); const [consentAccepted, setConsentAccepted] = useState(false); const [submissionStatus, setSubmissionStatus] = useState('');
  useEffect(() => { void Promise.all([json<Onboarding>('/api/worker/onboarding'), json<Overview>('/api/worker/overview'), json<{ tasks: Task[] }>('/api/tasks')]).then(([a,b,c]) => { setOnboarding(a); setOverview(b); setTasks(c.tasks); }).catch(() => setTaskStatus('Portal data is temporarily unavailable.')); }, []);
  async function askGuide(message: string) { if (!message.trim()) return; setReply('Finding the right next step…'); try { const data = await json<{ reply: string }>('/api/assistant', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ message }) }); setReply(data.reply); } catch (error) { setReply(error instanceof Error ? error.message : 'Guide unavailable'); } }
  async function connectWallet() { const ethereum = (window as Window & { ethereum?: { request: (args: { method: string; params?: unknown[] }) => Promise<string[]> } }).ethereum; if (!ethereum) return setWallet('No wallet detected'); try { const accounts = await ethereum.request({ method: 'eth_requestAccounts' }); const address = accounts[0]; if (!address) return; await ethereum.request({ method: 'wallet_switchEthereumChain', params: [{ chainId: '0x14a34' }] }); setWallet(`${address.slice(0, 6)}…${address.slice(-4)}`); } catch { setWallet('Connection declined'); } }
  function submit(event: FormEvent) { event.preventDefault(); void askGuide(question); setQuestion(''); }
  async function submitContribution(event: FormEvent) { event.preventDefault(); if (!selectedTask || !consentAccepted) return; setSubmissionStatus('Recording consent and submission…'); try { await json('/api/submissions', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ task_id: selectedTask.id, worker_name: workerName, consent: true }) }); setSubmissionStatus('Submitted for review. No reward or payment has been created.'); setWorkerName(''); setConsentAccepted(false); const data = await json<Overview>('/api/worker/overview'); setOverview(data); } catch (error) { setSubmissionStatus(error instanceof Error ? error.message : 'Submission unavailable'); } }
  return <>
    <header className="border-b border-slate-800 bg-slate-900/90 px-6 py-4"><div className="mx-auto flex max-w-6xl items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.24em] text-cyan-400">Worx contributor network</p><h1 className="mt-1 text-xl font-semibold">Worker portal</h1></div><button onClick={connectWallet} className="rounded-lg border border-slate-700 px-4 py-2 text-sm font-semibold hover:border-cyan-400">{wallet}</button></div></header>
    <main className="mx-auto max-w-6xl space-y-8 p-6">
      <section className="rounded-xl border border-amber-800 bg-amber-950/40 p-4 text-sm text-amber-100">Contribution consent is required. Rewards are recorded only after server-side review. Base Sepolia ERC-20 settlement requires a deployed contract and isolated oracle; ERC-20 transfers are not fiat cash-out. Do not submit personal, sensitive, or copyrighted material.</section>
      <section className="grid gap-4 md:grid-cols-4" aria-label="Workflow readiness"><Card title="Consent" value={onboarding?.consent.required ? `Required (${onboarding.consent.policy_version})` : 'Loading'} /><Card title="Uploads" value={onboarding ? onboarding.uploads.enabled ? 'Available' : 'Not configured' : 'Loading'} /><Card title="Identity verification" value={onboarding ? onboarding.identity_verification.enabled ? 'Available' : 'Not configured' : 'Loading'} /><Card title="Base Sepolia settlement" value={onboarding ? onboarding.settlement.enabled ? 'Available' : 'Not configured' : 'Loading'} /></section>
      <section className="grid gap-4 md:grid-cols-3"><Card title="Contribution status" prominent value={overview ? String(overview.contributions.length) : 'Loading'} /><Card title="Estimated rewards" prominent value="Not calculated" /><Card title="Settlement" prominent value={overview?.settlement.enabled ? `Base Sepolia: ${overview.settlement.network}` : 'Not configured'} /></section>
      <section className="grid gap-6 lg:grid-cols-[1.3fr_.7fr]"><article className="rounded-xl border border-slate-800 bg-slate-900 p-6"><p className="text-sm font-semibold text-cyan-400">1. Contribute off-chain</p><h2 className="mt-1 text-lg font-semibold">Choose a task</h2><div className="mt-5 grid gap-3 sm:grid-cols-2">{tasks.map((task) => <button key={task.id} onClick={() => { setSelectedTask(task); setTaskStatus(`${task.title}: ${task.instructions}`); setSubmissionStatus(''); }} className="rounded-lg border border-slate-700 p-4 text-left hover:border-cyan-400"><strong className="block">{task.title}</strong><span className="mt-1 block text-sm text-slate-400">{task.kind} · Review required · {task.reward_work} work units</span></button>)}</div><p className="mt-4 text-sm text-slate-300">{taskStatus}</p>{selectedTask && <form onSubmit={submitContribution} className="mt-5 space-y-3 rounded-lg border border-cyan-900 bg-slate-950 p-4"><p className="text-sm font-semibold">Submit: {selectedTask.title}</p><label className="block text-sm">Display name<input value={workerName} onChange={(event) => setWorkerName(event.target.value)} required maxLength={80} className="mt-1 block w-full rounded border border-slate-700 bg-slate-900 px-3 py-2" /></label><label className="flex items-start gap-2 text-sm text-slate-300"><input type="checkbox" checked={consentAccepted} onChange={(event) => setConsentAccepted(event.target.checked)} required className="mt-1" /><span>I consent to the current contribution policy ({onboarding?.consent.policy_version ?? 'loading'}). I will submit only requested data and understand this submission requires review.</span></label><button disabled={!consentAccepted} className="rounded-lg bg-cyan-500 px-4 py-2 text-sm font-semibold text-slate-950 disabled:cursor-not-allowed disabled:opacity-50">Submit for review</button>{submissionStatus && <p className="text-sm text-slate-300" aria-live="polite">{submissionStatus}</p>}</form>}</article><aside className="rounded-xl border border-slate-800 bg-slate-900 p-6"><p className="text-sm font-semibold text-cyan-400">2. Validate and settle</p><ol className="mt-4 space-y-3 text-sm text-slate-300"><li><strong>Validate:</strong> apply server-side quality and fraud checks.</li><li><strong>Calculate:</strong> record an off-chain reward estimate with an audit trail.</li><li><strong>Settle:</strong> use an approved batch process on a configured Base Sepolia environment.</li></ol><p className="mt-5 border-t border-slate-800 pt-4 text-xs text-slate-400">{overview?.reward_policy ?? 'Loading settlement policy.'}</p></aside></section>
      <section className="rounded-xl border border-violet-900 bg-violet-950/30 p-6"><p className="text-sm font-semibold text-violet-300">Synthetic-data workflow</p><h2 className="mt-1 text-lg font-semibold">Generated prompts require review</h2><p className="mt-2 text-sm text-slate-300">Generated data is draft-only and cannot be reward-eligible until an administrator verifies quality, rights, intended use, and contracted funding.</p></section>
      <section className="rounded-xl border border-slate-800 bg-slate-900 p-6"><div className="flex items-center justify-between"><h2 className="text-lg font-semibold">Contribution queue</h2><span className="text-sm text-slate-400">Preview records</span></div><div className="mt-4 space-y-3">{overview?.contributions.length ? overview.contributions.map((item) => <article key={item.id} className="flex items-center justify-between rounded-lg border border-slate-800 p-4"><div><p className="font-medium">{item.type}</p><p className="text-sm text-slate-400">{item.id}</p></div><div className="text-right text-sm"><p>{item.status}</p><p className="text-slate-400">{item.reward}</p></div></article>) : <p className="text-sm text-slate-400">No submissions have been recorded.</p>}</div></section>
      <section className="rounded-xl border border-cyan-900 bg-slate-900 p-6"><p className="text-sm font-semibold text-cyan-400">Portal guide</p><h2 className="mt-1 text-lg font-semibold">Ask for help navigating Worx</h2><div className="mt-4 flex flex-wrap gap-2">{['How do rewards work?','How do I connect my wallet?','Can I cash out?'].map((item) => <button onClick={() => void askGuide(item)} key={item} className="rounded-full border border-slate-700 px-3 py-1 text-sm hover:border-cyan-400">{item}</button>)}</div><form onSubmit={submit} className="mt-4 flex gap-2"><input value={question} onChange={(event) => setQuestion(event.target.value)} maxLength={500} required className="min-w-0 flex-1 rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm" placeholder="Ask a portal question"/><button className="rounded-lg bg-cyan-500 px-4 py-2 text-sm font-semibold text-slate-950 hover:bg-cyan-300">Ask</button></form><p className="mt-4 rounded-lg border border-slate-800 bg-slate-950 p-3 text-sm text-slate-300">{reply}</p></section>
    </main></>;
}
function Card({ title, value, prominent }: { title: string; value: string; prominent?: boolean }) { return <article className="rounded-xl border border-slate-800 bg-slate-900 p-4"><p className="text-xs uppercase tracking-wider text-slate-400">{title}</p><p className={`mt-2 font-semibold ${prominent ? 'text-2xl text-cyan-400' : ''}`}>{value}</p></article>; }
